import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from 'react';
import { LayoutDashboard, ShoppingCart, Package, WalletCards, BarChart3, Plus, Trash2, Save, LogOut, Pencil, ShieldCheck, UserRound, KeyRound } from 'lucide-react';
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer } from 'recharts';
import { jsPDF } from 'jspdf';
import { Printer, FileDown, X } from 'lucide-react';
import './styles.css';

type Role = 'admin' | 'cashier';
type User = { username: string; password: string; role: Role; label: string };
type Product = { id: string; name: string; size: string; price: number };
type Supplement = { id: string; name: string; price: number };
type Sale = { id: string; date: string; client: string; payment: string; total: number; items?: BasketLine[]; createdAt?: string };
type Expense = { id: string; date: string; category: string; label: string; amount: number };
type DB = { products: Product[]; supplements: Supplement[]; sales: Sale[]; expenses: Expense[] };
type BasketLine = { p: Product; q: number; s: Supplement[] };

const key = 'degue_manager_local_v1';
const authKey = 'degue_manager_session_v1';
const usersKey = 'degue_manager_users_v1';
const id = () => crypto.randomUUID();
const today = () => new Date().toISOString().slice(0, 10);
const money = (n: number) => new Intl.NumberFormat('fr-FR').format(n) + ' FCFA';
const DEFAULT_USERS: User[] = [
  { username: 'admin', password: 'admin123', role: 'admin', label: 'Administrateur' },
];
function loadUsers(): User[] {
  try { const raw = localStorage.getItem(usersKey); if (raw) { const parsed = JSON.parse(raw) as User[]; if (parsed.some(u => u.role === 'admin')) return parsed; } } catch {}
  localStorage.setItem(usersKey, JSON.stringify(DEFAULT_USERS)); return DEFAULT_USERS;
}
const makeSeed = (): DB => ({
  products: [{ id: id(), name: 'Dégué', size: '300 ml', price: 1000 }, { id: id(), name: 'Dégué', size: '500 ml', price: 1500 }],
  supplements: [{ id: id(), name: 'Lait', price: 200 }, { id: id(), name: 'Miel', price: 300 }], sales: [], expenses: [],
});
function load(): DB {
  const raw = localStorage.getItem(key);
  if (!raw) { const initial = makeSeed(); localStorage.setItem(key, JSON.stringify(initial)); return initial; }
  try { return JSON.parse(raw) as DB; } catch { const initial = makeSeed(); localStorage.setItem(key, JSON.stringify(initial)); return initial; }
}

export default function App() {
  const [d, setD] = useState<DB>(load);
  const [users, setUsers] = useState<User[]>(loadUsers);
  const saveUsers = (next: User[]) => { localStorage.setItem(usersKey, JSON.stringify(next)); setUsers(next); };
  const [user, setUser] = useState<User | null>(() => {
    try { const saved = sessionStorage.getItem(authKey); if (!saved) return null; const session = JSON.parse(saved) as Pick<User, 'username' | 'role' | 'label'>; return loadUsers().find(u => u.username === session.username && u.role === session.role) ?? null; } catch { return null; }
  });
  const [page, setPage] = useState('dashboard');
  const save = (next: DB) => { localStorage.setItem(key, JSON.stringify(next)); setD(next); };
  const login = (u: User) => { sessionStorage.setItem(authKey, JSON.stringify({ username: u.username, role: u.role, label: u.label })); setUser(u); setPage(u.role === 'admin' ? 'dashboard' : 'sales'); };
  const logout = () => { sessionStorage.removeItem(authKey); setUser(null); setPage('dashboard'); };
  useEffect(() => { if (user?.role === 'cashier' && !['sales', 'expenses'].includes(page)) setPage('sales'); }, [user, page]);

  if (!user) return <Login onLogin={login} />;
  const nav = user.role === 'admin'
    ? [['dashboard', 'Tableau de bord', LayoutDashboard], ['sales', 'Ventes', ShoppingCart], ['products', 'Produits', Package], ['expenses', 'Dépenses', WalletCards], ['reports', 'Rapports', BarChart3], ['accounts', 'Gestion des comptes', UserRound], ['profile', 'Mon compte', KeyRound]] as const
    : [['sales', 'Ventes', ShoppingCart], ['expenses', 'Dépenses', WalletCards]] as const;
  return <div className="shell"><aside><div className="brand"><div className="logo">D</div><div><b>Dégué Manager</b><small>Gestion journalière</small></div></div>
    <div className="user-chip"><div className="user-avatar">{user.role === 'admin' ? <ShieldCheck size={18}/> : <UserRound size={18}/>}</div><div><b>{user.label}</b><small>Connecté : {user.username}</small></div></div>
    <nav>{nav.map(([k, label, Icon]) => <button key={k} className={page === k ? 'active' : ''} onClick={() => setPage(k)}><Icon size={18}/>{label}</button>)}</nav>
    <button className="reset" onClick={logout}><LogOut size={17}/> Déconnexion</button>
  </aside><main>
    {page === 'dashboard' && user.role === 'admin' && <Dashboard d={d}/>}
    {page === 'sales' && <Sales d={d} save={save}/>}
    {page === 'products' && user.role === 'admin' && <Products d={d} save={save}/>}
    {page === 'expenses' && <Expenses d={d} save={save}/>}
    {page === 'reports' && user.role === 'admin' && <Reports d={d}/>}
    {page === 'accounts' && user.role === 'admin' && <CashierAccounts users={users} saveUsers={saveUsers}/>}
    {page === 'profile' && <MyAccount user={user} users={users} saveUsers={saveUsers} onUserUpdate={u => { setUser(u); sessionStorage.setItem(authKey, JSON.stringify({ username: u.username, role: u.role, label: u.label })); }}/>}
  </main></div>;
}

function Login({ onLogin }: { onLogin: (u: User) => void }) {
  const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState('');
  function submit(e: FormEvent) { e.preventDefault(); const found = loadUsers().find(u => u.username === username.trim() && u.password === password); if (!found) { setError('Identifiant ou mot de passe incorrect.'); return; } setError(''); onLogin(found); }
  return <div className="login-screen"><form className="login-card" onSubmit={submit}><div className="login-logo">D</div><h1>Dégué Manager</h1><p>Connecte-toi pour accéder à ton espace.</p><label>Identifiant<input autoComplete="username" value={username} onChange={e => setUsername(e.target.value)} placeholder="Ton identifiant" required/></label><label>Mot de passe<input type="password" autoComplete="current-password" value={password} onChange={e => setPassword(e.target.value)} placeholder="Ton mot de passe" required/></label>{error && <div className="login-error">{error}</div>}<button className="primary wide" type="submit">Se connecter</button></form></div>;
}
function CashierAccounts({ users, saveUsers }: { users: User[]; saveUsers: (users: User[]) => void }) {
  const [label, setLabel] = useState(''); const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [role, setRole] = useState<Role>('cashier'); const [error, setError] = useState(''); const [success, setSuccess] = useState('');
  const submit = (e: FormEvent) => { e.preventDefault(); const clean = username.trim(); if (!label.trim() || !clean || password.length < 6) { setError('Renseigne le nom, l’identifiant et un mot de passe de 6 caractères minimum.'); return; } if (users.some(u => u.username.toLowerCase() === clean.toLowerCase())) { setError('Cet identifiant existe déjà.'); return; } saveUsers([...users, { username: clean, password, role, label: label.trim() }]); setLabel(''); setUsername(''); setPassword(''); setRole('cashier'); setError(''); setSuccess(role === 'admin' ? 'Compte administrateur créé avec succès.' : 'Compte caissière créé avec succès.'); };
  return <Page title="Gestion des comptes" sub="Crée des accès caissières ou administrateurs. Seul un administrateur peut accéder à cette page."><div className="cols"><section className="card"><h2>Créer un compte</h2><form onSubmit={submit}><label>Type de compte<select value={role} onChange={e=>setRole(e.target.value as Role)}><option value="cashier">Caissière</option><option value="admin">Administrateur</option></select></label><label>Nom complet<input value={label} onChange={e=>setLabel(e.target.value)} placeholder="Ex. Ama" required/></label><label>Identifiant de connexion<input value={username} onChange={e=>setUsername(e.target.value)} autoComplete="off" placeholder="Ex. ama.caisse" required/></label><label>Mot de passe (6 caractères minimum)<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="new-password" minLength={6} required/></label>{error&&<div className="login-error">{error}</div>}{success&&<p className="success-message">{success}</p>}<button className="primary"><Plus size={16}/>Créer le compte</button></form></section><section className="card"><h2>Comptes enregistrés</h2><p className="muted">Les administrateurs gèrent l’application et les rapports. Les caissières enregistrent les ventes et dépenses.</p><div className="account-list">{users.map(u=><div className="account-row" key={u.username}><div><b>{u.label}</b><small>{u.username} · {u.role==='admin'?'Administrateur':'Caissière'}</small></div>{u.role==='cashier'&&<button className="danger icon" title="Supprimer le compte" onClick={()=>{if(confirm(`Supprimer le compte ${u.label} ?`))saveUsers(users.filter(x=>x.username!==u.username));}}><Trash2 size={15}/></button>}</div>)}</div></section></div></Page>;
}

function MyAccount({ user, users, saveUsers, onUserUpdate }: { user: User; users: User[]; saveUsers: (users: User[]) => void; onUserUpdate: (user: User) => void }) {
  const [current, setCurrent] = useState(''); const [next, setNext] = useState(''); const [confirmNext, setConfirmNext] = useState(''); const [error, setError] = useState(''); const [success, setSuccess] = useState('');
  const submit = (e: FormEvent) => { e.preventDefault(); if (current !== user.password) { setError('Le mot de passe actuel est incorrect.'); setSuccess(''); return; } if (next.length < 6) { setError('Le nouveau mot de passe doit contenir au moins 6 caractères.'); setSuccess(''); return; } if (next !== confirmNext) { setError('La confirmation ne correspond pas au nouveau mot de passe.'); setSuccess(''); return; } const updated = { ...user, password: next }; saveUsers(users.map(u => u.username === user.username ? updated : u)); onUserUpdate(updated); setCurrent(''); setNext(''); setConfirmNext(''); setError(''); setSuccess('Mot de passe modifié avec succès.'); };
  return <Page title="Mon compte" sub="Modifie le mot de passe de ton compte personnel."><section className="card account-password-card"><h2>Changer mon mot de passe</h2><p className="muted">Compte : <b>{user.username}</b> ({user.role === 'admin' ? 'Administrateur' : 'Caissière'})</p><form onSubmit={submit}><label>Mot de passe actuel<input type="password" value={current} onChange={e=>setCurrent(e.target.value)} autoComplete="current-password" required/></label><label>Nouveau mot de passe (6 caractères minimum)<input type="password" value={next} onChange={e=>setNext(e.target.value)} autoComplete="new-password" minLength={6} required/></label><label>Confirmer le nouveau mot de passe<input type="password" value={confirmNext} onChange={e=>setConfirmNext(e.target.value)} autoComplete="new-password" minLength={6} required/></label>{error&&<div className="login-error">{error}</div>}{success&&<p className="success-message">{success}</p>}<button className="primary"><KeyRound size={16}/>Mettre à jour le mot de passe</button></form></section></Page>;
}

function Page({ title, sub, children }: { title: string; sub: string; children: ReactNode }) { return <div className="page"><header><div><h1>{title}</h1><p>{sub}</p></div><span>{new Date().toLocaleDateString('fr-FR')}</span></header>{children}</div>; }
function Stat({ t, v, i }: { t: string; v: string; i: ReactNode }) { return <div className="stat"><div><small>{t}</small><h2>{v}</h2></div><i>{i}</i></div>; }
function Table({ title, heads, rows }: { title: string; heads: string[]; rows: ReactNode[][] }) { return <section className="card"><h2>{title}</h2><div className="scroll"><table><thead><tr>{heads.map((h,i)=><th key={i}>{h}</th>)}</tr></thead><tbody>{rows.length ? rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>) : <tr><td className="empty" colSpan={heads.length}>Aucune donnée.</td></tr>}</tbody></table></div></section>; }
function Dashboard({ d }: { d: DB }) { const s=d.sales.filter(x=>x.date===today()), e=d.expenses.filter(x=>x.date===today()), r=s.reduce((a,x)=>a+x.total,0), c=e.reduce((a,x)=>a+x.amount,0); return <Page title="Tableau de bord" sub="Vue globale de l'activité journalière."><div className="stats"><Stat t="Ventes du jour" v={String(s.length)} i={<ShoppingCart/>}/><Stat t="Chiffre d'affaires" v={money(r)} i={<BarChart3/>}/><Stat t="Dépenses" v={money(c)} i={<WalletCards/>}/><Stat t="Résultat du jour" v={money(r-c)} i={<LayoutDashboard/>}/></div><div className="cols"><Table title="Dernières ventes" heads={['Client','Paiement','Total']} rows={s.slice(0,8).map(x=>[x.client||'Comptoir',x.payment,money(x.total)])}/><Table title="Dernières dépenses" heads={['Libellé','Catégorie','Montant']} rows={e.slice(0,8).map(x=>[x.label,x.category,money(x.amount)])}/></div></Page>; }

function Products({ d, save }: { d: DB; save: (d: DB) => void }) {
  const [n,setN]=useState('Dégué'), [sz,setSz]=useState('300 ml'), [p,setP]=useState(''), [editing,setEditing]=useState<string|null>(null), [sn,setSn]=useState(''), [sp,setSp]=useState(''), [editingSup,setEditingSup]=useState<string|null>(null);
  const submitProduct=(e:FormEvent)=>{e.preventDefault();if(!n.trim()||!sz.trim()||p===''||Number(p)<0)return; if(editing)save({...d,products:d.products.map(x=>x.id===editing?{...x,name:n.trim(),size:sz.trim(),price:Number(p)}:x)});else save({...d,products:[...d.products,{id:id(),name:n.trim(),size:sz.trim(),price:Number(p)}]});setN('Dégué');setSz('300 ml');setP('');setEditing(null);};
  const editProduct=(x:Product)=>{setEditing(x.id);setN(x.name);setSz(x.size);setP(String(x.price));window.scrollTo({top:0,behavior:'smooth'});};
  const submitSup=(e:FormEvent)=>{e.preventDefault();if(!sn.trim()||sp===''||Number(sp)<0)return;if(editingSup)save({...d,supplements:d.supplements.map(x=>x.id===editingSup?{...x,name:sn.trim(),price:Number(sp)}:x)});else save({...d,supplements:[...d.supplements,{id:id(),name:sn.trim(),price:Number(sp)}]});setSn('');setSp('');setEditingSup(null);};
  return <Page title="Produits & suppléments" sub="Réservé à l'administrateur : création, modification et suppression."><div className="cols"><section className="card"><h2>{editing?'Modifier le produit':'Nouveau produit'}</h2><form onSubmit={submitProduct}><label>Nom du produit<input value={n} onChange={e=>setN(e.target.value)} required/></label><label>Format<input value={sz} onChange={e=>setSz(e.target.value)} placeholder="300 ml" required/></label><label>Prix (FCFA)<input type="number" min="0" value={p} onChange={e=>setP(e.target.value)} required/></label><div className="button-row"><button className="primary"><Save size={16}/>{editing?'Enregistrer les modifications':'Ajouter le produit'}</button>{editing&&<button type="button" className="secondary" onClick={()=>{setEditing(null);setN('Dégué');setSz('300 ml');setP('')}}>Annuler</button>}</div></form></section>
  <section className="card"><h2>{editingSup?'Modifier le supplément':'Nouveau supplément'}</h2><form onSubmit={submitSup}><label>Nom<input value={sn} onChange={e=>setSn(e.target.value)} placeholder="Lait, miel, fruit..." required/></label><label>Prix (FCFA)<input type="number" min="0" value={sp} onChange={e=>setSp(e.target.value)} required/></label><div className="button-row"><button className="primary"><Plus size={16}/>{editingSup?'Enregistrer':'Ajouter le supplément'}</button>{editingSup&&<button type="button" className="secondary" onClick={()=>{setEditingSup(null);setSn('');setSp('')}}>Annuler</button>}</div></form></section></div>
  <div className="cols"><Table title="Produits enregistrés" heads={['Produit','Format','Prix','Actions']} rows={d.products.map(x=>[x.name,x.size,money(x.price),<div className="button-row"><button className="icon" title="Modifier" onClick={()=>editProduct(x)}><Pencil size={15}/></button><button className="danger icon" title="Supprimer" onClick={()=>{if(confirm(`Supprimer ${x.name} ${x.size} ?`))save({...d,products:d.products.filter(y=>y.id!==x.id)})}}><Trash2 size={15}/></button></div>])}/><Table title="Suppléments enregistrés" heads={['Nom','Prix','Actions']} rows={d.supplements.map(x=>[x.name,money(x.price),<div className="button-row"><button className="icon" title="Modifier" onClick={()=>{setEditingSup(x.id);setSn(x.name);setSp(String(x.price));}}><Pencil size={15}/></button><button className="danger icon" title="Supprimer" onClick={()=>{if(confirm(`Supprimer le supplément ${x.name} ?`))save({...d,supplements:d.supplements.filter(y=>y.id!==x.id)})}}><Trash2 size={15}/></button></div>])}/></div></Page>;
}
function Sales({ d, save }: { d: DB; save: (d: DB) => void }) {
  const [pid,setPid]=useState(d.products[0]?.id||''),[qty,setQty]=useState(1),[ss,setSs]=useState<string[]>([]),[basket,setBasket]=useState<BasketLine[]>([]),[client,setClient]=useState(''),[pay,setPay]=useState('Espèces'),[receipt,setReceipt]=useState<Sale|null>(null);
  useEffect(()=>{if(!d.products.some(p=>p.id===pid))setPid(d.products[0]?.id||'')},[d.products,pid]);
  const total=basket.reduce((a,x)=>a+(x.p.price+x.s.reduce((z,y)=>z+y.price,0))*x.q,0);
  const add=(e:FormEvent)=>{e.preventDefault();const p=d.products.find(x=>x.id===pid);if(p)setBasket([...basket,{p,q:Math.max(1,qty),s:d.supplements.filter(x=>ss.includes(x.id))}]);setSs([]);setQty(1)};
  const finish=()=>{if(!basket.length)return;const sale:Sale={id:id(),date:today(),client,payment:pay,total,items:basket.map(x=>({...x,s:[...x.s]})),createdAt:new Date().toISOString()};save({...d,sales:[sale,...d.sales]});setBasket([]);setClient('');setReceipt(sale)};
  return <Page title="Ventes" sub="Enregistre les ventes journalières et imprime les reçus."><div className="sales"><section className="card"><h2>Ajouter au panier</h2><form onSubmit={add}><label>Produit<select value={pid} onChange={e=>setPid(e.target.value)} required>{d.products.map(p=><option key={p.id} value={p.id}>{p.name} - {p.size} — {money(p.price)}</option>)}</select></label><label>Quantité<input type="number" min="1" value={qty} onChange={e=>setQty(+e.target.value)} required/></label><div className="supp"><b>Suppléments</b>{d.supplements.map(s=><label className="check" key={s.id}><input type="checkbox" checked={ss.includes(s.id)} onChange={()=>setSs(v=>v.includes(s.id)?v.filter(x=>x!==s.id):[...v,s.id])}/>{s.name} (+{money(s.price)})</label>)}</div><button className="secondary" disabled={!d.products.length}><Plus size={16}/>Ajouter au panier</button></form><h3>Panier</h3>{basket.map((x,i)=><div className="line" key={i}><span>{x.q} × {x.p.name} {x.p.size}<small>{x.s.map(y=>y.name).join(', ')}</small></span><b>{money((x.p.price+x.s.reduce((a,z)=>a+z.price,0))*x.q)} <button className="icon danger" onClick={()=>setBasket(b=>b.filter((_,j)=>j!==i))}><Trash2 size={14}/></button></b></div>)}{!basket.length&&<p className="empty">Le panier est vide.</p>}</section><section className="card"><h2>Finaliser la vente</h2><label>Client<input value={client} onChange={e=>setClient(e.target.value)} placeholder="Facultatif"/></label><label>Paiement<select value={pay} onChange={e=>setPay(e.target.value)}><option>Espèces</option><option>TMoney</option><option>Flooz</option><option>Virement</option><option>Autre</option></select></label><div className="total"><span>Total</span><b>{money(total)}</b></div><button className="primary wide" disabled={!basket.length} onClick={finish}><Save size={17}/>Enregistrer et imprimer le reçu</button></section></div><Table title="Historique récent des ventes" heads={['Date','Client','Paiement','Total','Reçu']} rows={d.sales.slice(0,30).map(x=>[new Date((x.createdAt||x.date)+'T12:00:00').toLocaleDateString('fr-FR'),x.client||'Comptoir',x.payment,money(x.total),<button className="secondary" onClick={()=>setReceipt(x)}><Printer size={15}/> Reçu</button>])}/>
  {receipt&&<div className="modal-backdrop" onClick={()=>setReceipt(null)}><section className="receipt-modal" onClick={e=>e.stopPropagation()}><div className="no-print receipt-actions"><button className="secondary" onClick={()=>window.print()}><Printer size={16}/> Imprimer</button><button className="icon" onClick={()=>setReceipt(null)} aria-label="Fermer"><X size={18}/></button></div><Receipt sale={receipt}/></section></div>}
  </Page>;
}
function Receipt({sale}:{sale:Sale}) {
  return <div className="receipt-paper"><div className="receipt-center"><h2>Dégué Manager</h2><p>Reçu de vente</p></div><hr/><p><b>N° :</b> {sale.id.slice(0,8).toUpperCase()}</p><p><b>Date :</b> {new Date(sale.createdAt||sale.date).toLocaleString('fr-FR')}</p><p><b>Client :</b> {sale.client||'Client comptoir'}</p><p><b>Paiement :</b> {sale.payment}</p><hr/><table><thead><tr><th>Article</th><th>Qté</th><th>Total</th></tr></thead><tbody>{(sale.items||[]).map((x,i)=><tr key={i}><td>{x.p.name} {x.p.size}{x.s.length>0&&<small className="receipt-supp">Suppléments : {x.s.map(y=>y.name).join(', ')}</small>}</td><td>{x.q}</td><td>{money((x.p.price+x.s.reduce((a,y)=>a+y.price,0))*x.q)}</td></tr>)}</tbody></table><div className="receipt-total"><b>TOTAL À PAYER</b><strong>{money(sale.total)}</strong></div><p className="receipt-center">Merci pour votre achat !</p></div>;
}
function Expenses({ d, save }: { d: DB; save: (d: DB) => void }) { const[date,setDate]=useState(today()),[cat,setCat]=useState('Approvisionnement'),[label,setLabel]=useState(''),[amount,setAmount]=useState(''); return <Page title="Dépenses" sub="Enregistre toutes les sorties d'argent."><section className="card"><h2>Nouvelle dépense</h2><form className="expense" onSubmit={e=>{e.preventDefault();if(!label.trim()||amount===''||Number(amount)<0)return;save({...d,expenses:[{id:id(),date,category:cat,label:label.trim(),amount:Number(amount)},...d.expenses]});setLabel('');setAmount('')}}><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Catégorie<select value={cat} onChange={e=>setCat(e.target.value)}><option>Approvisionnement</option><option>Transport</option><option>Emballage</option><option>Électricité</option><option>Salaire</option><option>Autre</option></select></label><label>Libellé<input value={label} onChange={e=>setLabel(e.target.value)} required/></label><label>Montant<input type="number" min="0" value={amount} onChange={e=>setAmount(e.target.value)} required/></label><button className="primary"><Plus size={16}/>Enregistrer</button></form></section><Table title="Liste des dépenses" heads={['Date','Libellé','Catégorie','Montant','']} rows={d.expenses.map(x=>[new Date(x.date+'T12:00:00').toLocaleDateString('fr-FR'),x.label,x.category,money(x.amount),<button className="danger icon" onClick={()=>{if(confirm('Supprimer cette dépense ?'))save({...d,expenses:d.expenses.filter(y=>y.id!==x.id)})}}><Trash2 size={15}/></button>])}/></Page>; }
function Reports({ d }: { d: DB }) {
  const[from,setFrom]=useState(today()),[to,setTo]=useState(today());
  const s=d.sales.filter(x=>x.date>=from&&x.date<=to),e=d.expenses.filter(x=>x.date>=from&&x.date<=to),r=s.reduce((a,x)=>a+x.total,0),c=e.reduce((a,x)=>a+x.amount,0);
  const map:Record<string,{date:string;ventes:number;depenses:number}>={};s.forEach(x=>{map[x.date]??={date:x.date,ventes:0,depenses:0};map[x.date].ventes+=x.total});e.forEach(x=>{map[x.date]??={date:x.date,ventes:0,depenses:0};map[x.date].depenses+=x.amount});
  const exportPDF=()=>{const pdf=new jsPDF();pdf.setFontSize(18);pdf.text('Degue Manager - Rapport journalier',14,18);pdf.setFontSize(11);pdf.text(`Periode : ${from} au ${to}`,14,28);pdf.text(`Chiffre d'affaires : ${money(r)}`,14,40);pdf.text(`Total depenses : ${money(c)}`,14,49);pdf.text(`Resultat : ${money(r-c)}`,14,58);pdf.setFontSize(13);pdf.text('VENTES',14,72);pdf.setFontSize(9);let y=80;pdf.text('Date | Client | Paiement | Total',14,y);y+=7;s.forEach(x=>{if(y>275){pdf.addPage();y=18}const line=`${x.date} | ${(x.client||'Comptoir').slice(0,24)} | ${x.payment} | ${money(x.total)}`;pdf.text(line,14,y);y+=6});y+=5;if(y>270){pdf.addPage();y=18}pdf.setFontSize(13);pdf.text('DEPENSES',14,y);y+=8;pdf.setFontSize(9);e.forEach(x=>{if(y>280){pdf.addPage();y=18}pdf.text(`${x.date} | ${x.label.slice(0,30)} | ${x.category} | ${money(x.amount)}`,14,y);y+=6});pdf.save(`rapport-degue-${from}-${to}.pdf`)};
  return <Page title="Rapports" sub="Analyse par période et export PDF réservé à l'administrateur."><section className="card filters"><label>Du<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Au<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button className="primary" onClick={exportPDF}><FileDown size={17}/> Exporter le rapport en PDF</button></section><div className="stats"><Stat t="Chiffre d'affaires" v={money(r)} i={<ShoppingCart/>}/><Stat t="Dépenses" v={money(c)} i={<WalletCards/>}/><Stat t="Résultat" v={money(r-c)} i={<BarChart3/>}/></div><section className="card chart"><h2>Évolution journalière</h2><ResponsiveContainer><BarChart data={Object.values(map).sort((a,b)=>a.date.localeCompare(b.date))}><XAxis dataKey="date"/><YAxis/><Tooltip formatter={(v:any)=>money(Number(v))}/><Bar dataKey="ventes"/><Bar dataKey="depenses"/></BarChart></ResponsiveContainer></section><div className="cols"><Table title="Ventes de la période" heads={['Date','Client','Paiement','Total']} rows={s.map(x=>[new Date(x.date+'T12:00:00').toLocaleDateString('fr-FR'),x.client||'Comptoir',x.payment,money(x.total)])}/><Table title="Dépenses de la période" heads={['Date','Libellé','Catégorie','Montant']} rows={e.map(x=>[new Date(x.date+'T12:00:00').toLocaleDateString('fr-FR'),x.label,x.category,money(x.amount)])}/></div></Page>;
}
